---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: widen
    schedule:
      interval: monthly
    commit-message:
      prefix: deps
      prefix-development: chore(deps)
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: ci(deps)
