---
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - (main|master)
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
preset: conventionalcommits
presetConfig:
  types:  # {{ note_generator_rules | dump }}
releaseRules:  # {{ release_rules | dump }}
writerOpts:  # {{ templates | dump }}
changelogFile: CHANGELOG.md
message: |
  chore(release): ${nextRelease.version}

  ${nextRelease.notes}
assets:
  - CHANGELOG.md
